---
# tasks file for master_conf
- name: Docker installation
  package:
        name: "docker"
        state: present     
- name: Docker Service Start
  service:
        name: "docker"
        state: started
        enabled: yes
- name: Kubernetes Repo
  copy:
        src: "kubernetes.repo"
        dest: /etc/yum.repos.d/
        mode: 0644        
- name: Disable SELinux
  selinux:
    state: disabled
 # Write a script in your controller node at location /root/kubectl.txt. In that script write this command: sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
- name: Kubeadm, kubectl, kubelet installation
  script: /root/kubectl.txt
- name: Kubelet Starting
  service:
        name: "kubelet"
        state: started
        enabled: yes   
- name: Changing driver
  copy:
        src: daemon.json
        dest: /etc/docker/
        mode: 0644
- name: Restarting Docker Service
  service:
        name: "docker"
        state: restarted
- name: Pull images
  command: "kubeadm config images pull"
- name: iproute-tc installation
  package:
        name: "iproute-tc"
        state: present  
# Write another script at location /root/kubeadm.txt and write command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
- name: kubeadm init command
  script: /root/kubeadm.txt
  ignore_errors: true
  register: init 
- name: printing output of kubeadm init command
  debug:
        var: init      
- name: making directory
  shell: "sudo mkdir -p $HOME/.kube" 
- name: copying 
  copy: 
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config" 
- name: printing token
  command: "kubeadm token create --print-join-command"
  register: x 
- name: copying token command into file out.txt
  copy:
        content: "{{ x.stdout }}"
        dest: /root/out.txt      
- name: fetching out.txt from remote instance
  fetch:
        src: /root/out.txt
        dest: /root/
 # write script at /root/flannel.txt and command as : kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
- name: installing flannel
  script: /root/flannel.txt
