---
# tasks file for master_conf
- name: Docker installation
  package:
        name: "docker"
        state: present     
- name: Docker Service Start
  service:
        name: "docker"
        state: started
        enabled: yes
- name: Kubernetes Repo
  copy:
        src: "kubernetes.repo"
        dest: /etc/yum.repos.d/
        mode: 0644        
- name: Disable SELinux
  selinux:
    state: disabled
- name: Kubeadm, kubectl, kubelet installation
  command: "sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"  
- name: Kubelet Starting
  service:
        name: "kubelet"
        state: started
        enabled: yes   
- name: Changing driver
  copy:
        src: daemon.json
        dest: /etc/docker/
        mode: 0644
- name: Restarting Docker Service
  service:
        name: "docker"
        state: restarted
- name: Pull images
  shell: "kubeadm config images pull"
- name: iproute-tc installation
  package:
        name: "iproute-tc"
        state: present     
- name: kubeadm init command
  command: "kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: true
  register: init 
- name: printing output of kubeadm init command
  debug:
        var: init      
- name: making directory
  shell: "sudo mkdir -p $HOME/.kube" 
- name: copying 
  copy: 
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config" 
- name: printing token
  command: "kubeadm token create --print-join-command"
  register: x 
- name: copying token command into file out.txt
  copy:
        content: "{{ x.stdout }}"
        dest: /root/out.txt      
- name: fetching out.txt from remote instance
  fetch:
        src: /root/out.txt
        dest: /root/
- name: installing flannel
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
